# -*- coding: utf-8 -*-
"""squat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhTMtnlIRzEBZ1-hpHcLpHUynZRn5GoC
"""

!pip install tensorflow tensorflow-hub opencv-python numpy pandas
!apt-get install -y ffmpeg

from google.colab import files

uploaded = files.upload()
video_path = list(uploaded.keys())[0]

import tensorflow as tf
import tensorflow_hub as hub

model = hub.load("https://tfhub.dev/google/movenet/singlepose/lightning/4")
movenet = model.signatures['serving_default']

import numpy as np

def get_kp(frame):
    img = tf.image.resize_with_pad(frame, 192, 192)
    img = tf.cast(img, tf.int32)
    img = tf.expand_dims(img, axis=0)
    return movenet(img)['output_0'].numpy()[0][0]


def angle(a,b,c):
    a,b,c = np.array(a),np.array(b),np.array(c)
    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
    ang = abs(radians*180/np.pi)
    return 360-ang if ang>180 else ang

import cv2
import subprocess

cap = cv2.VideoCapture(video_path)

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = 30

ffmpeg = subprocess.Popen([
    'ffmpeg',
    '-y',
    '-f', 'rawvideo',
    '-vcodec', 'rawvideo',
    '-pix_fmt', 'bgr24',
    '-s', f'{w}x{h}',
    '-r', str(fps),
    '-i', '-',
    '-c:v', 'libx264',
    '-pix_fmt', 'yuv420p',
    'output.mp4'
], stdin=subprocess.PIPE)

counter = 0
stage = None
frame_id = 0

data = []

print("🚀 Processing video...")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_id += 1

    k = get_kp(frame)

    hip   = [k[11][1]*w, k[11][0]*h]
    knee  = [k[13][1]*w, k[13][0]*h]
    ankle = [k[15][1]*w, k[15][0]*h]

    ang = angle(hip,knee,ankle)

    # rep counter
    if ang > 160:
        stage = "up"

    if ang < 90 and stage == "up":
        stage = "down"
        counter += 1

    # draw skeleton
    import cv2
    cv2.circle(frame,(int(hip[0]),int(hip[1])),5,(0,255,0),-1)
    cv2.circle(frame,(int(knee[0]),int(knee[1])),5,(0,255,0),-1)
    cv2.circle(frame,(int(ankle[0]),int(ankle[1])),5,(0,255,0),-1)

    cv2.line(frame,(int(hip[0]),int(hip[1])),(int(knee[0]),int(knee[1])),(255,0,0),2)
    cv2.line(frame,(int(knee[0]),int(knee[1])),(int(ankle[0]),int(ankle[1])),(255,0,0),2)

    cv2.putText(frame,f"Reps: {counter}",(30,50),
                cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)

    cv2.putText(frame,f"Angle: {int(ang)}",(30,90),
                cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,0),2)

    # write to ffmpeg
    ffmpeg.stdin.write(frame.tobytes())

    data.append([frame_id,counter,ang])

cap.release()
ffmpeg.stdin.close()
ffmpeg.wait()

print("✅ Done! Video saved as output.mp4")

!pip install tensorflow tensorflow-hub opencv-python numpy pandas gtts
!apt-get install -y ffmpeg

import numpy as np

def get_kp(frame):
    img = tf.image.resize_with_pad(frame, 192, 192)
    img = tf.cast(img, tf.int32)
    img = tf.expand_dims(img, axis=0)
    return movenet(img)['output_0'].numpy()[0][0]


def angle(a,b,c):
    a,b,c = np.array(a),np.array(b),np.array(c)
    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
    ang = abs(radians*180/np.pi)
    return 360-ang if ang>180 else ang


def evaluate(ang):
    """
    تقييم التكنيك
    """
    if ang > 160:
        return "Standing", "GOOD", 10
    elif 90 <= ang <= 160:
        return "Squat", "GOOD", 9
    elif ang < 90:
        return "Too Deep", "RISK", 6
    else:
        return "Bad Form", "BAD", 4

from gtts import gTTS

def speak(text):
    tts = gTTS(text=text, lang='en')
    tts.save("voice.mp3")

import cv2
import subprocess
import pandas as pd

cap = cv2.VideoCapture(video_path)

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

ffmpeg = subprocess.Popen([
    'ffmpeg','-y',
    '-f','rawvideo',
    '-pix_fmt','bgr24',
    '-s',f'{w}x{h}',
    '-r','30',
    '-i','-',
    '-c:v','libx264',
    '-pix_fmt','yuv420p',
    'output.mp4'
], stdin=subprocess.PIPE)

counter = 0
stage = None
data = []

frame_id = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_id += 1

    k = get_kp(frame)

    hip   = [k[11][1]*w, k[11][0]*h]
    knee  = [k[13][1]*w, k[13][0]*h]
    ankle = [k[15][1]*w, k[15][0]*h]

    ang = angle(hip,knee,ankle)

    status, level, score = evaluate(ang)

    # عد التكرارات
    if ang > 160:
        stage = "up"

    if ang < 90 and stage == "up":
        stage = "down"
        counter += 1
        speak(f"Good rep {counter}")

    # رسم السكليتون
    cv2.circle(frame,(int(hip[0]),int(hip[1])),5,(0,255,0),-1)
    cv2.circle(frame,(int(knee[0]),int(knee[1])),5,(0,255,0),-1)
    cv2.circle(frame,(int(ankle[0]),int(ankle[1])),5,(0,255,0),-1)

    cv2.line(frame,(int(hip[0]),int(hip[1])),(int(knee[0]),int(knee[1])),(255,0,0),2)
    cv2.line(frame,(int(knee[0]),int(knee[1])),(int(ankle[0]),int(ankle[1])),(255,0,0),2)

    # النصوص
    cv2.putText(frame,f"Reps: {counter}",(30,50),
                cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)

    cv2.putText(frame,f"Angle: {int(ang)}",(30,90),
                cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,0),2)

    cv2.putText(frame,f"Status: {level}",(30,130),
                cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)

    ffmpeg.stdin.write(frame.tobytes())

    data.append([frame_id,counter,ang,level,score])

cap.release()
ffmpeg.stdin.close()
ffmpeg.wait()

print("✅ Done - Pro AI Coach finished")

df = pd.DataFrame(data, columns=[
    "frame","rep","angle","level","score"
])

df.to_csv("report.csv", index=False)

print("Total Reps:", df["rep"].max())
print("Average Score:", df["score"].mean())

from IPython.display import Video
Video("output.mp4", embed=True)

from google.colab import files

files.download("output.mp4")
files.download("report.csv")